---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest
- name: Install nginx
  yum:
    name: nginx
    state: latest
- name: Enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
- name: HTTP can pass the firewall
  firewalld:
    service: http
    state: enabled
    permanent: yes
    zone: public
  notify: Reload service firewalld
- name: Disabled selinux
  selinux:
    state: disabled
  notify: Restart service nginx
